package sv18120540_hibernate_pojo;
// Generated Jun 8, 2020 10:30:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Danhsachlop generated by hbm2java
 */
public class Danhsachlop  implements java.io.Serializable {


     private String malop;
     private Set lops = new HashSet(0);
     private Set tkbs = new HashSet(0);

    public Danhsachlop() {
    }

	
    public Danhsachlop(String malop) {
        this.malop = malop;
    }
    public Danhsachlop(String malop, Set lops, Set tkbs) {
       this.malop = malop;
       this.lops = lops;
       this.tkbs = tkbs;
    }
   
    public String getMalop() {
        return this.malop;
    }
    
    public void setMalop(String malop) {
        this.malop = malop;
    }
    public Set getLops() {
        return this.lops;
    }
    
    public void setLops(Set lops) {
        this.lops = lops;
    }
    public Set getTkbs() {
        return this.tkbs;
    }
    
    public void setTkbs(Set tkbs) {
        this.tkbs = tkbs;
    }




}


