package sv18120540_hibernate_pojo;
// Generated Jun 8, 2020 10:30:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DanhsachlopMonhoc generated by hbm2java
 */
public class DanhsachlopMonhoc  implements java.io.Serializable {


     private String malopMonhoc;
     private String stt;
     private Set diems = new HashSet(0);
     private Set lopMonhocs = new HashSet(0);

    public DanhsachlopMonhoc() {
    }

	
    public DanhsachlopMonhoc(String malopMonhoc) {
        this.malopMonhoc = malopMonhoc;
    }
    public DanhsachlopMonhoc(String malopMonhoc, String stt, Set diems, Set lopMonhocs) {
       this.malopMonhoc = malopMonhoc;
       this.stt = stt;
       this.diems = diems;
       this.lopMonhocs = lopMonhocs;
    }
   
    public String getMalopMonhoc() {
        return this.malopMonhoc;
    }
    
    public void setMalopMonhoc(String malopMonhoc) {
        this.malopMonhoc = malopMonhoc;
    }
    public String getStt() {
        return this.stt;
    }
    
    public void setStt(String stt) {
        this.stt = stt;
    }
    public Set getDiems() {
        return this.diems;
    }
    
    public void setDiems(Set diems) {
        this.diems = diems;
    }
    public Set getLopMonhocs() {
        return this.lopMonhocs;
    }
    
    public void setLopMonhocs(Set lopMonhocs) {
        this.lopMonhocs = lopMonhocs;
    }




}


