package sv18120540_hibernate_pojo;
// Generated Jun 8, 2020 10:30:35 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Diem generated by hbm2java
 */
public class Diem  implements java.io.Serializable {


     private DiemId id;
     private DanhsachlopMonhoc danhsachlopMonhoc;
     private Lop lop;
     private String hoten;
     private BigDecimal diemGk;
     private BigDecimal diemCk;
     private BigDecimal diemkhac;
     private BigDecimal diemtong;

    public Diem() {
    }

	
    public Diem(DiemId id, DanhsachlopMonhoc danhsachlopMonhoc, Lop lop) {
        this.id = id;
        this.danhsachlopMonhoc = danhsachlopMonhoc;
        this.lop = lop;
    }
    public Diem(DiemId id, DanhsachlopMonhoc danhsachlopMonhoc, Lop lop, String hoten, BigDecimal diemGk, BigDecimal diemCk, BigDecimal diemkhac, BigDecimal diemtong) {
       this.id = id;
       this.danhsachlopMonhoc = danhsachlopMonhoc;
       this.lop = lop;
       this.hoten = hoten;
       this.diemGk = diemGk;
       this.diemCk = diemCk;
       this.diemkhac = diemkhac;
       this.diemtong = diemtong;
    }
   
    public DiemId getId() {
        return this.id;
    }
    
    public void setId(DiemId id) {
        this.id = id;
    }
    public DanhsachlopMonhoc getDanhsachlopMonhoc() {
        return this.danhsachlopMonhoc;
    }
    
    public void setDanhsachlopMonhoc(DanhsachlopMonhoc danhsachlopMonhoc) {
        this.danhsachlopMonhoc = danhsachlopMonhoc;
    }
    public Lop getLop() {
        return this.lop;
    }
    
    public void setLop(Lop lop) {
        this.lop = lop;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public BigDecimal getDiemGk() {
        return this.diemGk;
    }
    
    public void setDiemGk(BigDecimal diemGk) {
        this.diemGk = diemGk;
    }
    public BigDecimal getDiemCk() {
        return this.diemCk;
    }
    
    public void setDiemCk(BigDecimal diemCk) {
        this.diemCk = diemCk;
    }
    public BigDecimal getDiemkhac() {
        return this.diemkhac;
    }
    
    public void setDiemkhac(BigDecimal diemkhac) {
        this.diemkhac = diemkhac;
    }
    public BigDecimal getDiemtong() {
        return this.diemtong;
    }
    
    public void setDiemtong(BigDecimal diemtong) {
        this.diemtong = diemtong;
    }




}


