package sv18120540_hibernate_pojo;
// Generated Jun 8, 2020 10:30:35 PM by Hibernate Tools 4.3.1



/**
 * LopMonhoc generated by hbm2java
 */
public class LopMonhoc  implements java.io.Serializable {


     private LopMonhocId id;
     private DanhsachlopMonhoc danhsachlopMonhoc;
     private Lop lop;
     private String hoten;
     private String gioitinh;
     private String cmnnd;

    public LopMonhoc() {
    }

	
    public LopMonhoc(LopMonhocId id, DanhsachlopMonhoc danhsachlopMonhoc, Lop lop) {
        this.id = id;
        this.danhsachlopMonhoc = danhsachlopMonhoc;
        this.lop = lop;
    }
    public LopMonhoc(LopMonhocId id, DanhsachlopMonhoc danhsachlopMonhoc, Lop lop, String hoten, String gioitinh, String cmnnd) {
       this.id = id;
       this.danhsachlopMonhoc = danhsachlopMonhoc;
       this.lop = lop;
       this.hoten = hoten;
       this.gioitinh = gioitinh;
       this.cmnnd = cmnnd;
    }
   
    public LopMonhocId getId() {
        return this.id;
    }
    
    public void setId(LopMonhocId id) {
        this.id = id;
    }
    public DanhsachlopMonhoc getDanhsachlopMonhoc() {
        return this.danhsachlopMonhoc;
    }
    
    public void setDanhsachlopMonhoc(DanhsachlopMonhoc danhsachlopMonhoc) {
        this.danhsachlopMonhoc = danhsachlopMonhoc;
    }
    public Lop getLop() {
        return this.lop;
    }
    
    public void setLop(Lop lop) {
        this.lop = lop;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public String getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }
    public String getCmnnd() {
        return this.cmnnd;
    }
    
    public void setCmnnd(String cmnnd) {
        this.cmnnd = cmnnd;
    }




}


