package sv18120540_hibernate_pojo;
// Generated Jun 8, 2020 10:30:35 PM by Hibernate Tools 4.3.1



/**
 * LopMonhocId generated by hbm2java
 */
public class LopMonhocId  implements java.io.Serializable {


     private String mssv;
     private String malopMonhoc;

    public LopMonhocId() {
    }

    public LopMonhocId(String mssv, String malopMonhoc) {
       this.mssv = mssv;
       this.malopMonhoc = malopMonhoc;
    }
   
    public String getMssv() {
        return this.mssv;
    }
    
    public void setMssv(String mssv) {
        this.mssv = mssv;
    }
    public String getMalopMonhoc() {
        return this.malopMonhoc;
    }
    
    public void setMalopMonhoc(String malopMonhoc) {
        this.malopMonhoc = malopMonhoc;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LopMonhocId) ) return false;
		 LopMonhocId castOther = ( LopMonhocId ) other; 
         
		 return ( (this.getMssv()==castOther.getMssv()) || ( this.getMssv()!=null && castOther.getMssv()!=null && this.getMssv().equals(castOther.getMssv()) ) )
 && ( (this.getMalopMonhoc()==castOther.getMalopMonhoc()) || ( this.getMalopMonhoc()!=null && castOther.getMalopMonhoc()!=null && this.getMalopMonhoc().equals(castOther.getMalopMonhoc()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMssv() == null ? 0 : this.getMssv().hashCode() );
         result = 37 * result + ( getMalopMonhoc() == null ? 0 : this.getMalopMonhoc().hashCode() );
         return result;
   }   


}


