package sv18120540_hibernate_pojo;
// Generated Jun 8, 2020 10:30:35 PM by Hibernate Tools 4.3.1



/**
 * Taikhoan generated by hbm2java
 */
public class Taikhoan  implements java.io.Serializable {


     private String tendangnhap;
     private String matkhau;
     private String loaitk;

    public Taikhoan() {
    }

	
    public Taikhoan(String tendangnhap) {
        this.tendangnhap = tendangnhap;
    }
    public Taikhoan(String tendangnhap, String matkhau, String loaitk) {
       this.tendangnhap = tendangnhap;
       this.matkhau = matkhau;
       this.loaitk = loaitk;
    }
   
    public String getTendangnhap() {
        return this.tendangnhap;
    }
    
    public void setTendangnhap(String tendangnhap) {
        this.tendangnhap = tendangnhap;
    }
    public String getMatkhau() {
        return this.matkhau;
    }
    
    public void setMatkhau(String matkhau) {
        this.matkhau = matkhau;
    }
    public String getLoaitk() {
        return this.loaitk;
    }
    
    public void setLoaitk(String loaitk) {
        this.loaitk = loaitk;
    }




}


