package sv18120540_hibernate_pojo;
// Generated Jun 8, 2020 10:30:35 PM by Hibernate Tools 4.3.1



/**
 * Tkb generated by hbm2java
 */
public class Tkb  implements java.io.Serializable {


     private TkbId id;
     private Danhsachlop danhsachlop;
     private String tenmon;
     private String phonghoc;

    public Tkb() {
    }

	
    public Tkb(TkbId id, Danhsachlop danhsachlop) {
        this.id = id;
        this.danhsachlop = danhsachlop;
    }
    public Tkb(TkbId id, Danhsachlop danhsachlop, String tenmon, String phonghoc) {
       this.id = id;
       this.danhsachlop = danhsachlop;
       this.tenmon = tenmon;
       this.phonghoc = phonghoc;
    }
   
    public TkbId getId() {
        return this.id;
    }
    
    public void setId(TkbId id) {
        this.id = id;
    }
    public Danhsachlop getDanhsachlop() {
        return this.danhsachlop;
    }
    
    public void setDanhsachlop(Danhsachlop danhsachlop) {
        this.danhsachlop = danhsachlop;
    }
    public String getTenmon() {
        return this.tenmon;
    }
    
    public void setTenmon(String tenmon) {
        this.tenmon = tenmon;
    }
    public String getPhonghoc() {
        return this.phonghoc;
    }
    
    public void setPhonghoc(String phonghoc) {
        this.phonghoc = phonghoc;
    }




}


